# Generated by Django 5.0.3 on 2024-04-21 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('date', models.DateField(null=True)),
                ('categories', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='blog_images/')),
                ('extra', models.CharField(max_length=200)),
            ],
        ),
    ]
