# Generated by Django 5.0.3 on 2024-04-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0002_gymimage_opend_gymimage_picname_gymimage_picurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gymmedia/')),
            ],
        ),
        migrations.RemoveField(
            model_name='gymimage',
            name='image',
        ),
    ]
