# Generated by Django 5.0.3 on 2024-04-26 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0003_alter_blog_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msgfrom', models.TextField()),
                ('msg', models.CharField(max_length=100)),
                ('msgextra', models.CharField(max_length=60)),
            ],
        ),
    ]
