# Generated by Django 5.0.3 on 2024-05-07 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0006_rename_orderp_orderequ_rename_orders_orderpoduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='msgdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderpoduct',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
