# Generated by Django 5.0.3 on 2024-05-07 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymapp', '0007_messages_msgdate_orderpoduct_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderequ',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordersupli',
            name='product_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
