[build]
publish = "gymapp"  # Point to the directory containing both templates and static files
command = "python manage.py collectstatic --noinput"

[[redirects]]
from = "/*"
to = "/templates/front/index.html"
status = 200